main: eu.endercentral.crazy_advancements.CrazyAdvancementsAPI
name: CrazyAdvancementsAPI
version: 2.1.3
api-version: 1.13
load: startup
author: ZockerAxel
commands:
  grant:
    usage: /grant <Player> <Manager> <Advancement> [Criteria...]
    description: Grants <Advancement>-[Criteria...] to <Player> in <Manager>
    aliases: [cagrant]
  revoke:
    usage: /revoke <Player> <Manager> <Advancement> [Criteria...]
    description: Revokes <Advancement>-[Criteria...] from <Player> in <Manager>
    aliases: [carevoke]
  setprogress:
    usage: /setprogress <Player> <Manager> <Advancement> <Number>
    description: Sets <Advancement> Progress for <Player> in <Manager>
    aliases: [caprogress]
  showtoast:
    usage: /showtoast <Player> <Icon> <Message>
    description: Displays a Toast Advancement Message
    aliases: [catoast, toast]